default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  redis:
    host: redis://<%= ENV["REDIS_HOSTNAME"] %>:6379
    options:
      :namespace: <%= ENV["DATABASE_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  database: skrc_test

staging:
  <<: *default

production:
  <<: *default
